---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: chaos-nginx
spec:
  monitoring: false
  jobCleanUpPolicy: delete
  appinfo:
    appns: default
    applabel: 'app=nginx'
    appkind: deployment
  chaosServiceAccount: nginx
  experiments:
    - name: pod-delete
      spec:
        components:
          - name: FORCE
            value: 'false'

