---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
  labels:
    app: cp-kafka
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-sa
rules:
- apiGroups: ["", "apps", "batch", "litmuschaos.io"]
  resources: ["pods","deployments","jobs","pods/exec","statefulsets","configmaps","chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs : ["get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-sa
subjects:
- kind: ServiceAccount
  name: kafka-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kafka-sa
  apiGroup: rbac.authorization.k8s.io

