---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
  labels:
    app: cp-kafka
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-sa
rules:
- apiGroups: ["", "extensions", "apps", "batch", "litmuschaos.io"]
  resources: ["daemonsets", "statefulsets", "deployments", "replicasets", "jobs", "pods", "pods/exec", "events", "chaosengines", "chaosexperiments", "chaosresults"]
  verbs: ["*"] 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-sa
subjects:
- kind: ServiceAccount
  name: kafka-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kafka-sa
  apiGroup: rbac.authorization.k8s.io

