apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  appinfo: 
    appns: default
    applabel: "app=nginx"
  experiments:
    - name: pod-delete 
      spec:
        rank: 1
    - name: container-kill
      spec:
        rank: 2 
  schedule:
    interval: ""
    excludedTimes: ""
    excludedDays: ""
    concurrencyPolicy: "" 
